### PR TITLE
Bug/fix library jsx use effect issues

### PR DESCRIPTION
**Pull request by BlackBond06**
This PR resolves issue #160 opened by @gbowne1.

Changes Made:
- Added setFilter prop to Library component.
- Added clean up function to the useEffect to clean up setMyRows and setFilter functions when component unmounts.
- Added 'myRows' to the dependency array of useEffect.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review
- [x] Manually reviewed browser console for errors/warnings

This change does appear to fix the useEffect issue #161 and this change also does not appear to cause additional errors.

Thank you for the opportunity to review your PR for merging.

Approving for merge.  Looking forwards to seeing some working tests with Jest, etc.

**Review by LOGESH-B — APPROVED** [review]
Hii @BlackBond06 
Thanks for your contribution 
Approving for merge🙌

**Comment by gbowne1** [comment]
@BlackBond06 That was your 5th successful merge.  I sent you a Collaborator invite.  Thanks so much!for all of your great contributions.  Welcome aboard.

**Comment by LOGESH-B** [comment]
Welcome buddy @BlackBond06 🤝🙌

**Comment by BlackBond06** [comment]
Yay!!! Thank you @gbowne1 @LOGESH-B

**Comment by gbowne1** [comment]
You're welcome! @BlackBond06

**Pull request merged**
