### PR TITLE
Add-a-create-profile-feature

### PR DESCRIPTION
**Pull request by BlackBond06**
This PR implements the first part of the profile feature, which includes creating and updating a user profile.
To implement this feature, the following changes were made:

- Created an alert modal to inform users about creating their profile.
- Created a profile form for collecting profile data.
- Utilized ipinfo.io library to get the country and city info of users.
- Created profile component for displaying users profile data.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- Checked out this change locally for testing and review for merge

This looks excellent.  I tested in Firefox and Chrome.  Doesn't seem to introduce any significant errors or warnings.  

Approving for merge

**Comment by gbowne1** [comment]
@BlackBond06, I really like that set of features.  Looks really nice.

**Review by LOGESH-B — APPROVED** [review]
Hiii @BlackBond06 
Great Work🧑‍💻,Working as expected

when the image is more than 500kb can't able to post showing large payload not able to poast

**Comment by BlackBond06** [comment]
> Hiii @BlackBond06 Great Work🧑‍💻,Working as expected
> 
> when the image is more than 500kb can't able to post showing large payload not able to post

Is it for the user profile pic or background image that you noticed this ?

**Comment by LOGESH-B** [comment]
> > Hiii @BlackBond06 Great Work🧑‍💻,Working as expected
> > when the image is more than 500kb can't able to post showing large payload not able to post
> 
> Is it for the user profile pic or background image that you noticed this ?

for userprofile @BlackBond06

**Pull request merged**
