### PR TITLE
added books table sorting feature #40

### PR DESCRIPTION
**Pull request by Vishwanath760970**
@gbowne1 I have implemented the books table sorting feature, for all the columns.

Refer below gif for fix working in my local.

codebooker issue 3 #40

It seems the table pagination feature implementation, has some complexities in implementing and needs more time, so I will take it up by creating another separate issue in coming days.

But with respect to this PR, please review and merge it.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Checked out this change locally for testing.

This change appears to work as the PR shows.

Approving for merge.


Keep in mind that this view is the users own library.  All of these entries would get added to the global database if the book was not foumd. Furthermore, book reviews would get added to global scope as well.

We need to implement the main part of the app which would show everyones added books and reviews.

Not sure how to best go about this.

**Comment by Vishwanath760970** [comment]
> Checked out this change locally for testing.
> 
> This change appears to work as the PR shows.
> 
> Approving for merge.
> 
> Keep in mind that this view is the users own library. All of these entries would get added to the global database if the book was not foumd. Furthermore, book reviews would get added to global scope as well.
> 
> We need to implement the main part of the app which would show everyones added books and reviews.
> 
> Not sure how to best go about this.

We need to implement the logic for user account creation and have views for current user dashboard,
and a separate dashboard for global books dashboard.
the logged in user can add books to global dashboard and mark a book as his favorite to his account collection.
For this we need to implement the backend logic with database.
and also some application routes using a routing library, to display different screens as global dashboard and, specific user dashboard.

**Comment by gbowne1** [comment]
@Vishwanath760970 yes we should.  Theres no user land stuff done yet.  New issue time?

**Comment by Vishwanath760970** [comment]
> @Vishwanath760970 yes we should.  Theres no user land stuff done yet.  New issue time?

Yeah, there's nothing done yet for creating new users or users landing page, guess you need to create a new issue for it.

**Pull request merged**
