### PR TITLE
Update title and description

### LINKED ISSUE #197: Bug: title is still defaulted to React App
**Describe the bug**
The Title and description is as default which we get after create-react-app.

**To Reproduce**

Open the homepage and check the tab title.

**Expected behavior**
 - Title and description should tell more about the application.

### PR DESCRIPTION
**Pull request by akshitarora921**
closes #197

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review for merge.

This does appear to fix the title of the app and includes a description.

**Review by BlackBond06 — APPROVED** [review]
Changes in this PR works as described, updating the title and description of the app. Thank you @akshitarora921 for the opportunity to review your PR

**Comment by akshitarora921** [comment]
@BlackBond06 thank you for the review 🚀

**Review by LOGESH-B — APPROVED** [review]
Thanks for your Contribution @akshitarora921 🙌
This PR fixes the issue as described

**Pull request merged**
