### PR TITLE
#2 issue fixed

### LINKED ISSUE #2: [TODO] Add a dark mode/light mode theme toggle
Add a dark mode/light mode theme toggle using the Switch toggle in the TopNav.

Light mode theme should use the white and blue, but could be other colors.  

If you build a theme controller, use red, orange, yellow, green, blue, indigo, violet. With possibly a way to let user pick from those colors.

Dark mode theme should be some combination of black, grey, white.

### PR DESCRIPTION
**Pull request by k-deepak04**
#2 light dark theme added on toggle and table design as

### CODE REVIEW

**Comment by k-deepak04** [comment]
#12 done
This one took me straight 2 hours 🥲

**Comment by k-deepak04** [comment]
#12 
I also fixed the table in this one . earlier it below the header and hidden.

**Comment by gbowne1** [comment]
Thanks @k-deepak04 Will review the PR.  Thank you for the opportunity to review your PR.

**Review by gbowne1 — APPROVED** [review]
Checked out and tested this code locally and it appears to function as suggested by the screenshots. Thank you for your PR.

Approving this for merging and merged.

**Pull request merged**
