### PR TITLE
Feature/capture feedback

### PR DESCRIPTION
**Pull request by vktr-r2**

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review for merging
- [x] Manually reviewed the new features in browser for new errors/warnings
- [x] Manually reviewed the code for spelling and other syntax issues

This PR change implements a Feedback feature to capture user feedback.

It does not appear to add any additional warnings or errors.

Approving for merge.  Thank you for the opportunity to review your PR!

**Review by LOGESH-B — APPROVED** [review]
Hii @vktr-r2 
Tested Locally Approving for Merge
Thanks for you Cotriibution🙌

**Review by BlackBond06 — APPROVED** [review]

**Comment by BlackBond06** [comment]
Hi @vktr-r2 
Tested changes locally, approved for merging.
Thank you for the opportunity to review your PR!

**Comment by gbowne1** [comment]
@BlackBond06 Use the green Review button at the top of the PR to submit your review. You will get a popup to review the PR, with options to comment, request changes or approve.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews

**Comment by gbowne1** [comment]
@victor20m In the future, please enter a description of your changes in the desciption box of the PR.  

Merging this PR. 

Thanks for your contribution!

**Comment by BlackBond06** [comment]
@gbowne1 I still need to add a comment after I have approved the changes ?

**Comment by gbowne1** [comment]
no, it may not have picked up that. But I looked and I see it did now.  thanks @BlackBond06

**Pull request merged**
