### PR TITLE
Feat/add tailwindcss on top of mui

### PR DESCRIPTION
**Pull request by BlackBond06**
This PR introduces the integration of TailwindCSS alongside Material-UI version 5 (MUI v5) in our project.

### Changes Made
- Added TailwindCSS as a CSS utility framework.
- Removed nested styles from BookSearch.css to address Tailwind nesting style error.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing for review and merg
- [x] Manuallly reviewed browser console for errors and warnings
- [x] Manually reviewed for spelling, grammar and syntax errors.

This change adds Tailwind CSS to improve and enhance the MUI styling we are already using. It does not appear to add any additional errors or warnings to the app. It will improve our styling greatly.

Approving for merge

**Review by LOGESH-B — COMMENTED** [review]
Hii @BlackBond06 
 Thank you for the oppotunity to review your PR for merging
 This code not producing any error but I got one warning.Is anybody getting this?
 
image

**Comment by BlackBond06** [comment]
No I did not get that error. But I'll look into it. Has the issue been merged?

**Comment by gbowne1** [comment]
Not been merged yet.

**Comment by gbowne1** [comment]
I merged the other two PR's, sync and see what is working now.

**Comment by BlackBond06** [comment]
@LOGESH-B, I still dont get the error. can you make a video so I know where it is coming from ?

**Review by LOGESH-B — APPROVED** [review]
Hii @BlackBond06 
The error is now resolved...I don't know where it araises from...
Approving for merge🙌

**Pull request merged**
