### PR TITLE
fixes #220 added empty depedency in useEffect

### LINKED ISSUE #220: Title: Infinite Fetching Loop and Memory Leak in fetchBooksFromDB Function
**Describe the bug**
The `fetchBooksFromDB` function triggers an infinite loop of data fetching when used in conjunction with `useEffect`, leading to significant performance degradation and a memory leak.

### Expected Behavior
`fetchBooksFromDB` should fetch the data once and stop, without causing an infinite loop or memory leaks.

### Actual Behavior
The function continuously fetches data without stopping, causing browser performance issues and memory leaks.

### Additional Information
memoryLeak

### PR DESCRIPTION
**Pull request by love-sonkar**
fixedd #220 

i have added an empty depedency array in useEffect to stop infinite loop fetching issue.

Screenshot 2024-10-06 205940

### CODE REVIEW

**Comment by gbowne1** [comment]
We have tried to fix this issue before @love-sonkar.

**Review by gbowne1 — APPROVED** [review]
This PR fixes the infinite fetching loop by adding a empty dependency array 

We have tried fixing this issue before. 

Library.jsx is a huge file and really needs broken down into other things. 

Approving this PR for merge 

Thanks for the opportunity to review your PR and for your contribution

**Review by LOGESH-B — APPROVED** [review]
Adding empty array prevents the infinite call of the fetchBooksFromDB()

**Review by BlackBond06 — APPROVED** [review]
Changes in this PR works as expected, without any bugs. This effectively stops the continuing rendering of fetched books.

**Pull request merged**
