### PR TITLE
Feature/registration redirect

### PR DESCRIPTION
**Pull request by vktr-r2**
Resolves [Issue 172](https://github.com/gbowne1/codebooker/issues/172):

**Files Changed:**
- userController.js
- Register.jsx

**In userController.js:**
1. Updated signup function to generate new token during registration process
2. Updated signup function to send registration confirmation email upon successful registration

**In Register.jsx:**
1. Import useNavigate from react-router-dom to handle navigation
2. Update handleRegister function to save token and user in local storage
3. Redirect to home route after 200 response received

https://github.com/gbowne1/codebooker/assets/122321007/d3f50fc1-6b0a-4483-93f1-d8843b689f91

Screenshot 2023-09-20 at 20 52 59

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review for merging
- [x] Manually reviewed for syntax and grammar errors 
- [x] Reviewed the PR description and related issue for context.

Tested this change and it appears this adds a feature to redirect during the registration progress.

It also does not appear to cause any additional warnings outside of ones that already exist in the browser console or in ESLint.

Approving for merge.  Thank you for the opportunity to review your PR @vktr-r2 !

**Comment by gbowne1** [comment]
1 more PR cycle and I will invite you to be a collaborator! Thanks for your contribution!

**Review by LOGESH-B — APPROVED** [review]
Hii @vktr-r2 
Thanks for youur contribution🙌
Approving for merge

**Review by BlackBond06 — APPROVED** [review]
Tested changes made in PR locally for errors. Changes works as described in PR, updating the Registration/SignUp feature. Approving for merge.

**Pull request merged**
