### PR TITLE
Updated some libraries

### PR DESCRIPTION
**Pull request by Mayor-Rhymes**

### CODE REVIEW

**Comment by gbowne1** [comment]
@Mayor-Rhymes 

This only has the package.lock file.  It should include the package.json file as well.  You can commit that to the same branch.  Did it update your package.json?

**Comment by Mayor-Rhymes** [comment]
Weirdly enough, it didn't. It was after I had sent the PR that I realized
that. I will check it out and see what I can do.

**Comment by Mayor-Rhymes** [comment]
I have updated both the package.json and the package-lock.json

**Review by gbowne1 — APPROVED** [review]
Looks like this updated the packages as expected.

Approving for merge.

**Pull request merged**
