### PR TITLE
fragment issue fixed

### LINKED ISSUE #155: [BUG] MUI Menu doesn't accept a Fragment as a child error
Sometimes I get this warning in console and it doesn't seem to matter which route I am navigated to.

```shell
MUI: The Menu component doesn't accept a Fragment as a child.
Consider providing an array instead.[ line 3 > eval:1:10146](http://localhost:3000/%20line%203%20%3E%20eval)
    <anonymous> line 3 > eval:1
    Menu Menu.js:132
    React 4
    Menu Menu.js:126
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    (Async: EventHandlerNonNull)
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        fn
        js
        js
        factory
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        fn
        js
        factory
        __webpack_require__
        <anonymous>
        <anonymous>
  ```

### PR DESCRIPTION
**Pull request by ratishjain12**
fixes #155 

fixed that fragment issue

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review
- [x] Manually reviwed for errors in browser console.

This change fixes #155 and now does not give the MUI Menu.. error.

Thank you for the opportunity to review your PR! @ratishjain12

**Comment by ratishjain12** [comment]
Ok let me check

**Comment by gbowne1** [comment]
@ratishjain12 Sorry, I meant to say it's fine. No more of the fragment errors. I checked again

**Comment by ratishjain12** [comment]
So its mergeable now?

**Review by LOGESH-B — APPROVED** [review]
Thanks for your contribution @ratishjain12

**Pull request merged**
