### PR TITLE
Running ESLint and Prettier on entire codebase

### LINKED ISSUE #89: [TODO] Re-Linting and Prettifying the entire code base
Now that we have a good working ESLint and Prettier configuration the entire codebase needs Prettier and ESLint writing and fixing to the entire project.

This will help us keep the codebase clean, styled uniformly and largely free of formatting and linting problems.

### PR DESCRIPTION
**Pull request by gbowne1**
Now that we have aworking ESLint and Prettier configurations, beyond the default/base configuration that Create React App gives us, we should lint and prettify our code make our code uniform across all code.

This PR covers running ESLint and Prettier across the entire codebase so that our code is:

- maintainable
- styled correctly
- uniform across all code

It also fixes #89

### CODE REVIEW

**Review by LOGESH-B — COMMENTED** [review]
Hii @gbowne1 
I got this even after runninig the commands on root folder
npx prettier --write .
npx eslint --fix .

image

**Comment by gbowne1** [comment]
@LOGESH-B  That's fine, those are just missing imports.  I left a bunch of defines in App.js that we never used in App.js and actually they could be cleaned up/removed (anything that is in imports that doesn't exist in the rest of the App.js) 

There are react auto-import tools we can use that will import stuff from libraries, etc automatically

We still have prop types issues with:

BookSearch.jsx
SideNav.jsx
PopUpState.jsx
Library.jsx

which I can make a separate issue for.  

The rest that are left are unused variables that were used but didnt get whatever needed to make it work.

**Comment by gbowne1** [comment]
Here's the list I get:

```shell
[eslint] 
src/App.js
  Line 3:5:   'styled' is defined but never used            no-unused-vars
  Line 4:5:   'alpha' is defined but never used             no-unused-vars
  Line 12:8:  'Button' is defined but never used            no-unused-vars
  Line 13:8:  'IconButton' is defined but never used        no-unused-vars
  Line 14:8:  'MenuIcon' is defined but never used          no-unused-vars
  Line 15:8:  'AccountCircle' is defined but never used     no-unused-vars
  Line 17:8:  'FormControlLabel' is defined but never used  no-unused-vars
  Line 18:8:  'FormGroup' is defined but never used         no-unused-vars
  Line 19:8:  'MenuItem' is defined but never used          no-unused-vars
  Line 20:8:  'Menu' is defined but never used              no-unused-vars
  Line 21:8:  'MailIcon' is defined but never used          no-unused-vars
  Line 23:8:  'MoreIcon' is defined but never used          no-unused-vars
  Line 24:8:  'Container' is defined but never used         no-unused-vars
  Line 25:8:  'SettingsIcon' is defined but never used      no-unused-vars
  Line 26:8:  'Avatar' is defined but never used            no-unused-vars
  Line 27:8:  'AdbIcon' is defined but never used           no-unused-vars
  Line 28:8:  'InputBase' is defined but never used         no-unused-vars
  Line 29:8:  'SearchIcon' is defined but never used        no-unused-vars
  Line 31:8:  'Divider' is defined but never used           no-unused-vars
  Line 32:8:  'List' is defined but never used              no-unused-vars
  Line 33:8:  'ListItem' is defined but never used          no-unused-vars
  Line 34:8:  'ListItemButton' is defined but never used    no-unused-vars
  Line 35:8:  'ListItemText' is defined but never used      no-unused-vars
  Line 36:8:  'Paper' is defined but never used             no-unused-vars
  Line 37:8:  'Fab' is defined but never used               no-unused-vars
  Line 38:8:  'ListItemAvatar' is defined but never used    no-unused-vars
  Line 39:8:  'ListSubheader' is defined but never used     no-unused-vars
  Line 40:8:  'useScrollTrigger' is defined but never used  no-unused-vars
  Line 41:8:  'Rating' is defined but never used            no-unused-vars
  Line 42:8:  'Slide' is defined but never used             no-unused-vars
  Line 44:8:  'logo' is defined but never used              no-unused-vars
  Line 48:8:  'Setting' is defined but never used           no-unused-vars

src/components/BookSearch/BookSearch.jsx
  Line 3:8:   'SearchIcon' is defined but never used       no-unused-vars
  Line 6:25:  'matches' is missing in props validation     react/prop-types
  Line 6:34:  'filter' is missing in props validation      react/prop-types
  Line 6:42:  'setFilter' is missing in props validation   react/prop-types
  Line 6:53:  'isDarkMode' is missing in props validation  react/prop-types

src/components/Library/Library.jsx
  Line 2:8:     'PropTypes' is defined but never used              no-unused-vars
  Line 4:10:    'alpha' is defined but never used                  no-unused-vars
  Line 5:10:    'useTheme' is defined but never used               no-unused-vars
  Line 7:8:     'Collapse' is defined but never used               no-unused-vars
  Line 10:21:   'tableCellClasses' is defined but never used       no-unused-vars
  Line 12:8:    'TableFooter' is defined but never used            no-unused-vars
  Line 15:8:    'TablePagination' is defined but never used        no-unused-vars
  Line 19:8:    'FirstPageIcon' is defined but never used          no-unused-vars
  Line 20:8:    'KeyboardArrowLeft' is defined but never used      no-unused-vars
  Line 21:8:    'KeyboardArrowRight' is defined but never used     no-unused-vars
  Line 22:8:    'LastPageIcon' is defined but never used           no-unused-vars
  Line 23:8:    'KeyboardArrowDownIcon' is defined but never used  no-unused-vars
  Line 24:8:    'KeyboardArrowUpIcon' is defined but never used    no-unused-vars
  Line 26:8:    'Toolbar' is defined but never used                no-unused-vars
  Line 28:8:    'Checkbox' is defined but never used               no-unused-vars
  Line 29:8:    'Tooltip' is defined but never used                no-unused-vars
  Line 30:8:    'FormControlLabel' is defined but never used       no-unused-vars
  Line 31:8:    'Switch' is defined but never used                 no-unused-vars
  Line 32:8:    'DeleteIcon' is defined but never used             no-unused-vars
  Line 33:8:    'FilterListIcon' is defined but never used         no-unused-vars
  Line 34:10:   'visuallyHidden' is defined but never used         no-unused-vars
  Line 49:20:   'SnackbarOrigin' is defined but never used         no-unused-vars
  Line 65:35:   'filter' is missing in props validation            react/prop-types
  Line 389:41:  Missing "key" prop for element in iterator         react/jsx-key

src/components/SearchPopup/PopupState.jsx
  Line 2:8:    'Typography' is defined but never used       no-unused-vars
  Line 3:8:    'Button' is defined but never used           no-unused-vars
  Line 9:10:   'size' is defined but never used             no-unused-vars
  Line 10:10:  'Fullscreen' is defined but never used       no-unused-vars
  Line 14:5:   'isDarkMode' is missing in props validation  react/prop-types
  Line 15:5:   'filter' is missing in props validation      react/prop-types
  Line 16:5:   'setFilter' is missing in props validation   react/prop-types
  Line 17:5:   'matches' is missing in props validation     react/prop-types

src/components/SideNav/SideNav.jsx
  Line 15:8:   'SchoolIcon' is defined but never used                no-unused-vars
  Line 18:8:   'PsychologyIcon' is defined but never used            no-unused-vars
  Line 27:35:  'setfilter' is missing in props validation            react/prop-types
  Line 35:27:  'buttonProps' is missing in props validation          react/prop-types
  Line 35:40:  'name' is missing in props validation                 react/prop-types
  Line 35:46:  'label' is missing in props validation                react/prop-types
  Line 35:53:  'icon' is missing in props validation                 react/prop-types
  Line 35:59:  'expandable' is missing in props validation           react/prop-types
  Line 39:29:  'buttonProps.onClick' is missing in props validation  react/prop-types

Search for the keywords to learn more about each error.
```

**Comment by gbowne1** [comment]
Made the first issue about unused imports.

**Pull request merged**
