### PR TITLE
Profile fix and API documentation

### PR DESCRIPTION
**Pull request by bmacarini**
The GetProfile function requests the userEmail, but email data was not previously requested in the Profile model and saved in the newProfile function. I have fixed this issue.

Additionally, I have added a link to the CodeBooker API documentation in the README file.

### CODE REVIEW

**Review by gbowne1 — CHANGES_REQUESTED** [review]
@bmacarini 

Your email / profile changes worked great

I would like to recommend that you clone the wiki.. clone link on the Wiki tab and put your API docs there.  Your API docs link takes someone to your personal GitHub.io page outside of the project.

We will be putting API docs in both the Wiki and the docs folder.

I will allow you to push directly to the codebooker Wiki repo, as currently there really is no API docs as of yet

Thanks and if you have any questions you can tag our current collaborators and myself @gbowne1 @LOGESH-B @BlackBond06

**Review by BlackBond06 — APPROVED** [review]
Hi @bmacarini,

Changes to the Profile feature works as expected without any errors or bugs. Please implement the changes requested by @gbowne1, so the PR can be merged.

Thank you for the opportunity to review your PR.

**Comment by bmacarini** [comment]
Thank you, @gbowne1 and @BlackBond06. I'll make the changes.

Regarding the API documentation link redirecting to my personal GitHub.io page, you can follow these steps to use @gbowne1's GitHub.io page:

1. Go to: https://github.com/bmacarini/codebooker-documentation
2. Click on the "Use this template" button.
3. In the new repository, go to "Settings".
4. On the left-side menu, navigate to "Pages".
5. Under "Build and deployment," select the "Master" branch, choose "/root," and then click "Save".

After completing these steps, you can access the API documentation at: https://gbowne1.github.io/{repository_name}/

If you need any help, please let me know.

**Comment by gbowne1** [comment]
@bmacarini 

I think you have to be a contributor or collaborator in order to PR or commit and push to the Wiki.  I'm not familiar with the permissions needed for the Wiki.

**Review by gbowne1 — APPROVED** [review]

**Comment by gbowne1** [comment]
@bmacarini 

Was there a reason why you used YAML for the API documentation in  /docs? We are not using or consuming YAML only Markdown docs in our process.

I think only having the wiki and /docs folder are fine and not have the user need to go outside of the project.

This repo will eventually get moved to its own org repo as github com/codebooker/ so we can add a codebooker.github.io at that time 

Also, while using github.io is fine, i think thats outside the scope right now 

Thoughts @bmacarini @LOGESH-B @BlackBond06, etc?

**Comment by bmacarini** [comment]
@gbowne1 

I created the API documentation using Swagger, which uses YAML. I opted for this tool because it generates a page that provides more context about the routes and allows developers to test them. Although they have to leave the project page to access it, I believe it greatly enhances the development experience.

**Comment by gbowne1** [comment]
I haven't used Swagger, so I don't know.  I don't also know if anyone else used/uses Swagger with this project either.

You can add docs in Markdown.  

I use Postman and Postman as well as MongoDB extensions in VSCode to work with this project.. 

We will be creating an API eventually that other services can consume for programming/coding/software development books.  

We aren't too far off from migrating to a org so we can create tools for this app as well as for these:

Please feel free to also contribute to:

https://github.com/gbowne1/reactsocialnetwork
https://github.com/gbowne1/ProgrammerNotes
https://github.com/gbowne1/TwitchBot
https://github.com/gbowne1/fashion-marketplace
https://github.com/gbowne1/gbowne1site_react
https://github.com/gbowne1/RadioLogger
https://github.com/gbowne1/spmssite
https://github.com/gbowne1/SavvyBudget

**Comment by gbowne1** [comment]
This can be merged as is, so merging and closing this.

**Pull request merged**
