### PR TITLE
Added new recommendations

### PR DESCRIPTION
**Pull request by Karutoh**
Added three books for recommendation. First, "Game Engine Architecture", second, "Digital Audio Theory: A Practical Guide" and finally, "Game Physics Cookbook".

### CODE REVIEW

**Comment by BlackBond06** [comment]
@gbowne1, can't find this issue on the issues list.

**Comment by gbowne1** [comment]
It's not in the issues list, @BlackBond06.  This contribution is basically contributing to the intial database through the data.json file.   I still have to add all of my books, and there's 300 of them. 

As an aside, the data.json is broken.  Most of the entries in the json are missing the "category" field, all but the first entry.  Can we create a garbage collector utility to grab the data from the json and stuff it in the database?  There is also no "id" or "_id" field.  Yes I know we have the database, but there should be some other way that would work in case the database ever goes down, even a short term outage.  

@Karutoh @BlackBond06 @LOGESH-B

**Review by gbowne1 — APPROVED** [review]
This change is manually adding several new books to the app, via the data.json and can be merged without 

Approving this for merge.

As a side note, per my comment in the conversation, there should be some way of entering data, should the database ever be down.  I have a feature and a couple code snippits to share that I would like to propose for this.

**Review by BlackBond06 — APPROVED** [review]
This PR adds more books to the data.js file. Approving for merge. Thanks for the opportunity to review your PR.

**Comment by BlackBond06** [comment]
@gbowne1, your request for an alternative way to fetch books if the database develops problem, is very sound and I support 100%.

**Comment by gbowne1** [comment]
Yes, @BlackBond06 

A non existent database, or an outage, unless it was a planned outage, would probably be rare, but it is an edge case I would like to solve and a pretty good feature to have a workaround for.

**Comment by Karutoh** [comment]
> Yes, @BlackBond06 
> 
> A non existent database, or an outage, unless it was a planned outage, would probably be rare, but it is an edge case I would like to solve and a pretty good feature to have a workaround for.

Instead of adding them manually. You could just have an option to cache them locally anytime you've connected with the database. Store a time stamp inside the file so you can determine when it was last updated and if it should be updated.

**Comment by gbowne1** [comment]
Thats a great idea too.

**Review by LOGESH-B — APPROVED** [review]
Hii @Karutoh 
Thanks for your contribution🙌

@gbowne1 @BlackBond06 @Karutoh 
If we catch the data.json it will be reflected in the all the PR in the develeopement....so we need to put it in gitignore

**Comment by gbowne1** [comment]
@LOGESH-B We should consider continuing to use it in the edge case if the database is missing, down for maintaining, problems with the database, or just offline in general.. we could probably figure out some way.  I added the issue #179

**Pull request merged**
