### PR TITLE
Feature/forgot password

### PR DESCRIPTION
**Pull request by BlackBond06**
[FEAT] Add a Forgot Password feature. #126

This PR introduces the 'Forgot Password' functionality to the CodeBooker app, in response to a help-wanted issue raised by @gbowne1. It includes the following changes:

- Added a new API endpoint for handling forgot password requests.

- Created a new API endpoint for resetting passwords using a token.

- Implemented frontend components (Forgot password, and ResetPassword pages) for the 'Forgot Password' feature.

- Integrated email sending using nodemailer to deliver password reset links.

- Improved user experience with loading indicators and error handling.

This feature enhances user account security by allowing them to request a password reset when needed. It also improves the overall user experience by providing a seamless way to recover forgotten passwords.

PIC1: forgotPassword;

PIC2 : resetPassword;

PIC3: reset password mail

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Checked out this change locally for testing.

It appears that all parts of the forgot password functionality works as described by the PR.

Approving for merge.

Thanks for the opportunity to review your PR.

**Review by LOGESH-B — CHANGES_REQUESTED** [review]
Hii @BlackBond06 
Thanks for your contribution✌️

I Have some trouble I don't know wheather you are getting this.

* I can't able to register to new user because you made the "resetpasswod" in user model as required but not updated during signup(Suggestion:Removing required)
* You are not deleting the token from the user after using the token
* You are not checking the valitity of the token(i.e either expired or not) using the jwt

Can you able to address this..... feel free to comment on this

Clerifiication in person,
* Could you tell me why you installed mongodb

Suggestion/may be future suggestion,
* Storing the tokens in seperate model collections
* Deleting it after sometime automatically (using TTL)

@gbowne1 I am getting prettier warnings,did you?

Thanks for the opportunity to review your PR.🙌

**Comment by BlackBond06** [comment]
Hi @LOGESH-B, thank you for your review. I'll will make the necessary changes suggested. I think I will go with your suggestion of creating a separate token model.

As for why I installed MongoDB, I was having trouble setting it up locally, read the doc, which said to install MongoDB before use. I did that and got it running.

**Comment by gbowne1** [comment]
There is no problem with adding mongodb node driver package to the dependencies at all. It can even be installed on both server and client package.json not just server @LOGESH-B  @BlackBond06 and keep in mind the driver is separate from mongoose ORM package.

We definitely can use separate auth collections for tokens, etc. In fact that's recommended for storing authentication & authorization items in mongodb unless we are going to specifically rely on the browser storage by itself.

@LOGESH-B I did not get any prettier warnings.  Not terribly worried about prettier in this change.  We can do a clean up soon.  

I did test the new feature. Nodemailer does send an email.

The additional UI made in this PR is fine.  

At this point we should start working on some login testing work with Jest because all of the normal features are now existing with a Login.test.js in a test folder.  I can make a issue for login system testing.

**Comment by BlackBond06** [comment]
Hii @LOGESH-B, I've made the following suggested changes, please review:

i. Created Token model with expiration handling.
ii. Remove resetPassword property from user mode, which solved the bug @LOGESH-B  noticed.
iii. Token deletes automatically on expiration (currently set to 30min from creation)

**Review by gbowne1 — APPROVED** [review]
-[x] Checked out the updates to this change locally for testing and review.
-[x] Reviewed for errors in browser console

Having a look through the updated code, looks like this should work just fine and the code looks clean through all of the changes.  

Approving for merge.

**Comment by LOGESH-B** [comment]
> There is no problem with adding mongodb node driver package to the dependencies at all. It can even be installed on both server and client package.json not just server @LOGESH-B @BlackBond06 and keep in mind the driver is separate from mongoose ORM package.
> 
> We definitely can use separate auth collections for tokens, etc. In fact that's recommended for storing authentication & authorization items in mongodb unless we are going to specifically rely on the browser storage by itself.
> 
> @LOGESH-B I did not get any prettier warnings. Not terribly worried about prettier in this change. We can do a clean up soon.
> 
> I did test the new feature. Nodemailer does send an email.
> 
> The additional UI made in this PR is fine.
> 
> At this point we should start working on some login testing work with Jest because all of the normal features are now existing with a Login.test.js in a test folder. I can make a issue for login system testing.

Yeah, but I think it not neccessary. Is there any specific reason for installing the driver....Because in my previous projects I am not suppposed to install mongodb driver

**Comment by gbowne1** [comment]
Well, as you saw, it solved @BlackBond06's problem setting it up locally. 

 The `mongodb` nodejs driver package in fact should be there especially if you use MongoDB locally.  It's in the documentation and is recommended.  Not everyone will need it, especially those with MongoDB Atlas or Compass.  

From some research and reading  the docs, " If you are using React, Node.js, and Express to connect to a MongoDB database, you will need to install the MongoDB Node.js driver package `mongodb`. The MongoDB Node.js driver is the official driver provided by MongoDB for connecting and interacting with a MongoDB database from a Node.js application."

It will be just fine.  I suspect without it some people contributing will have a similar problem without it.

**Review by LOGESH-B — APPROVED** [review]
Great Work ✌️

Everything looks fine, Approving for merge

Doubts:
* Wheather we really in need of JWT token.As we are using the TTL index there is no use of JWT token right🤷‍♂️

**Comment by gbowne1** [comment]
Alright, merging.  

@LOGESH-B as for your doubts we can definitely improve our use of the browser, storage, etc. There a few ways we could go with this.  

My only concerns are security issues.  

Now that more features are falling into place, we can definitely work on improvements. Again more developer documentation will be helpful.

**Pull request merged**
