### PR TITLE
Feature/adding new book to db

### PR DESCRIPTION
**Pull request by BlackBond06**
This pull request introduces a new feature that allows users to add and books to the database. The feature includes the following changes:

-Update Book Schema Definition: Updated the book schema to include a userId that ties a book to it's owner(the user that added it). This is so that only a book owner can delete a book from the app. Also updated the book schema property 'isbn' from type 'number' to type 'string'. This is because ISBN numbers are alphanumeric characters (includes numbers and strings), which if  it is set as number would produces a cast error when uploading to db.

- Updated API Endpoint for Book Creation:  API endpoint has been updated to facilitate the addition of books to the database. Users can provide book details, and the backend validates the input before creating a new book entry associated with the respective user.

- New API Endpoint for Book Deletion: A new API endpoint has been created to facilitate the deletion of books from the database. Users can only delete books they own, that is books they added.

-Book Deletion Functionality: Building on the addition feature, this enhancement also includes the ability to delete books from the database. Users can only delete books that they have added, ensuring a secure and controlled environment.

- Feedback and Responses: The API responses have been carefully crafted to provide users with meaningful feedback, including success messages and error descriptions.

https://github.com/gbowne1/codebooker/assets/100074330/2438bbd1-3d70-4ce9-983b-7f06062e0acf

FURTHER UI ADDITIONS:
- Changed book addition icon
- Used MUI moreHerizIcon to indicate hidden content

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review
- [x] Manually reviewed all commits for errors

This change adds better features to the functionality that already exists to add books to the table, only now it will add to the database.

This change does not appear to add any significant errors, warnings or other bugs and works as expected.  More testing might be necessary once we actually start adding books to the DB.

Thanks for the opportunity to review your PR @BlackBond06 

Approving for merge.

**Review by LOGESH-B — APPROVED** [review]
Hii @BlackBond06 
Thanks for your contribution✌️

Tested Locally Working fine....

My sugession is that why we need to show the delete and edit option to all the user...it can be restricted right🤷‍♂️

**Comment by gbowne1** [comment]
@LOGESH-B 

yes it could be restricted.  I mean it would probably be better if we merge this then add a issue. Only logged in users should be able to edit their own library.  And not be able to edit the global.

**Comment by BlackBond06** [comment]
@LOGESH-B all users can see the delete and edit button when they click on the ellipsis icon which indicates more content but only owners can delete their book and also edit their book.

**Comment by LOGESH-B** [comment]
Hii @BlackBond06  yes, the validation are done at backend its good, but it is unnecessary you are showing it to all user

**Comment by BlackBond06** [comment]
Yea @LOGESH-B I think I see you point. So it should only be visible to users who has added a book right ?

**Comment by LOGESH-B** [comment]
Yeah...

**Comment by BlackBond06** [comment]
I think I can make that adjustments. Can I go ahead ?

**Pull request merged**
