### PR TITLE
Get books from file and seed database when DB is empty

### PR DESCRIPTION
**Pull request by Priyankaa2503**
Fixes Issue #179 

This PR : 
1) Seeds the database with default books using existing JSON data to prevent loading issues when the database is empty.
2) In addition to this, the user can see a "add book" option.
Screenshot 2023-10-22 at 8 01 01 PM

### CODE REVIEW

**Review by LOGESH-B — COMMENTED** [review]
Hii @Priyankaa2503  Great work✌️
I think its better to do this in startup file(server/setup),instead of doing it in client side,because initialy there is no books in db for all developers. 
It difinitly going to add the local file books to db on 1st render. so it can be moved to setup file

This flow only happend in dev mode. So we can seperate the dev functions to made  feature refactor easy

@gbowne1  If you think its ok for now then it can be merged 
Tested Locally ,All loooks good.
Thanks for giving opportunity for review your  @Priyankaa2503

**Review by gbowne1 — APPROVED** [review]
I tested this with the database running and not running.  Appears to fix most if not all of the issues that this change addresses as noted in previous.

Approving for merge.  Thank you for the opportunity to review your PR and for your contribution @Priyankaa2503

**Comment by gbowne1** [comment]
yeah, I think it will be ok to merge this.  

This should take care of several problems with this

- Loading whatever books are available in the database.
- If there is no database available (not created or if the database is down), it should use the json data instead.
- Prevent long loading times resulting in a page loading spinner
- possibly other issues

**Review by BlackBond06 — COMMENTED** [review]
Populating the UI with book data from data.json file, per this current change happens when db is empty and not when there is a problem with the server. Isn't this action (populating the UI with books from data.json file) suppose to happen when there is an actual error from the db and not when the db is empty ? I think if the db is empty the 'addbook' button should be displayed along with a message informing the user that the db is empty.

**Comment by gbowne1** [comment]
"I think if the db is empty the 'addbook' button should be displayed along with a message informing the user that the db is empty."

Yes, thats correct @BlackBond06 

"Isn't this action (populating the UI with books from data.json file) suppose to happen when there is an actual error from the db and not when the db is empty?"

It should probably do both, but when the db is empty you should get a message saying it is empty and it needs to be populated.  Normally this wouldn't happen, but.. one never knows when it might not, unless an outage is scheduled.  Also because we will likely need some visible data in the UI during development several things can happen:

- Add books to the db using the UI
- seed the database from the json data
- Let the user know theres no books in the database

**Comment by BlackBond06** [comment]
With the current state of app, changes in this PR will populate the UI from Json data, when the app loads, since the db is empty. After adding a book, the app state will change from displaying all that json data to showing only the added book. Don't know if this is a good user experience.

**Comment by gbowne1** [comment]
It might not be the best UX, but I think it could be impoved upon with some work.

In production, it would be relatively unlikely there would be no books in the database as we would want 100% uptime or as near as possible,  unless the database was down for maintenance.. and at that point the user would only have their library (if they had any) showing in their "Library" tab in the left nav drawer.

We still have to add that UI for the Library tab.

**Comment by LOGESH-B** [comment]
> With the current state of app, changes in this PR will populate the UI from Json data, when the app loads, since the db is empty. After adding a book, the app state will change from displaying all that json data to showing only the added book. Don't know if this is a good user experience.

No, if you add a book both the data is shown(i.e from Json,added book) because the json data is added to the db at initial render

**Comment by gbowne1** [comment]
Yeah, that sounds a lot more like it to me @LOGESH-B

**Comment by BlackBond06** [comment]
> > With the current state of app, changes in this PR will populate the UI from Json data, when the app loads, since the db is empty. After adding a book, the app state will change from displaying all that json data to showing only the added book. Don't know if this is a good user experience.
> 
> No, if you add a book both the data is shown(i.e from Json,added book) because the json data is added to the db at initial render

Oh okay, that looks good then. Thank you for the clarification @LOGESH-B.

**Comment by gbowne1** [comment]
@BlackBond06 @LOGESH-B can we now review this?

**Review by BlackBond06 — APPROVED** [review]
Changes in this PR works as described, seeding the UI with books  from json data when db is empty. Thanks for the opportunity to review your PR @Priyankaa2503. Approving for merge.

**Review by LOGESH-B — APPROVED** [review]
Thanks for the contribution @Priyankaa2503

**Pull request merged**
