### PR TITLE
Style the login and register page

### LINKED ISSUE #113: [TODO] Style the login and register page
The Login.jsx and Register.jsx are completely unstyled pages

Style them using the Login.css and Register.css

### PR DESCRIPTION
**Pull request by kabszac**
This PR closes #113  I worked on the login page and made changes to login.jsx and login.css 
@gbowne1  
oldsignin
the new sign in:
newsignin

I made changes to the register.jsx to add styling.
Old Sign up:
oldsignup
New sign up:
newsignup

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review

This change adds styling to the login and register pages and appears as expected in the browser view and also the screenshots provided with this PR.

Approving for merge.

Thanks for your contribution @kabszac

**Review by LOGESH-B — CHANGES_REQUESTED** [review]
Hii @kabszac 
Great Work and Ui also looks simple and neat

I got one issue with the mobile view of signin Page
I Attached the Image below
image


* Can you work on that(Signin Page) to make it responsive 
* And also make link to only Signin text you make Link to all (i.e Already Have Account)text

I am mensioning this because its not big deal now but it is a small change that can be done now

Otherwise functionality wise all good✅✌️

**Comment by gbowne1** [comment]
@LOGESH-B. 

Mobile styling is a completely different and separate issue.  I made a separate issue #79 specific to this. 

This can PR be merged as is and then we can work on mobile and responsive styling.

**Review by LOGESH-B — APPROVED** [review]
Thanks for your contribution  @kabszac 
Approve for merge

**Comment by kabszac** [comment]
@LOGESH-B 'And also make link to only Signin text you make Link to all (i.e Already Have Account)text'. I did not understand what I'm supposed to do here.

**Pull request merged**
