### PR TITLE
Fixing .variable-env and Home.jsx component

### LINKED ISSUE #143: [BUG] useEffect has a missing dependency
After the recent merges and features, I am now getting this warning/error:

[eslint] 
src/pages/Home/Home.jsx
  Line 58:8:  React Hook useEffect has a missing dependency: 'location.state.loggin'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/pages/Home/Home.jsx
  Line 58:8:  React Hook useEffect has a missing dependency: 'location.state.loggin'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

webpack compiled with 1 warning

I thought this may be because login is misspelled `loggin`, but even with correcting the spelling still has a missing dep warning.

### PR DESCRIPTION
**Pull request by gbowne1**
- [x] Tested this locally to make sure that the App will now render with no ESLint errors or warnings.

This PR fixes the useEffect in the Home.jsx component so that the app will render.  This might need some more cleanup work in the future, but am returning the component to working status anyways.

This PR also fixes the .variable.env file so that it can be more easily used to set up the project.

Edit: this will also fix #143

### CODE REVIEW

**Review by LOGESH-B — APPROVED** [review]
Hii @gbowne1 
Did you have some sample books data ... We can write code on setup.js file to insert in the db Which will be added to db on the initial run of setup.js

**Comment by gbowne1** [comment]
@LOGESH-B 

That would be a huge task as I have well over 300 books on coding/programming.  That would be near impossible by hand.  The books I entered on data.json are all valid books. That data could be used. I am not sure that all of them need done for setup, only a few to get the data entry started.

**Comment by LOGESH-B** [comment]
Yes we can have some 10 to 20 books for now,that we can add by default at running of setup file...Instead of showing nothing/(data from data.json file) on initial home page we can render the books from db

**Comment by gbowne1** [comment]
Yeah, agreed. Well the data I had in data.json are actual books so that could be used.

**Pull request merged**
