### PR TITLE
scripts to run the frontend and the server seperately or at once

### PR DESCRIPTION
**Pull request by prime1999**
Created the scripts to run the frontend and the backend of the app separately of together from the root of the application,

script to run the frontend: npm start
script to run the server: npm run server
script to run both together: npm run dev

### CODE REVIEW

**Review by gbowne1 — CHANGES_REQUESTED** [review]
Please leave the .variable.env file in as it is a part of the Registration email process. The user would fill in this .env file.  

Otherwise this looks ok.

**Review by LOGESH-B — APPROVED** [review]
Approving for merge.
What is the use concurrently package?

**Review by gbowne1 — APPROVED** [review]

**Comment by prime1999** [comment]
it can be used to run more than one scripts at once, so I am using it to run the frontend and backend at once , like instead of saying npm start then also using np run server that I prepared for the backend, we can just directly run npm run dev that is using concurrently to run but the start and run server command

**Review by BlackBond06 — APPROVED** [review]
@prime1999 thank you for your contribution.
Approving for merge.

**Pull request merged**
