### PR TITLE
remove/warnings

### PR DESCRIPTION
**Pull request by LOGESH-B**
Hii @gbowne1 

I can't get the dependency error but I get another error that location.state.loggin is undefined
But it also resolved once I logged in again 
I removes the Prettier errors On this PR 
(Solves issue #143 )

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review 
- [x] manually reviewed for styling and errors

This change mostly does a prettify cleanuo of the code which is needed to eliminate code styling errors that exist.

I will test more in the afternoon tomorrow and possibly fix the rest of the issue then.  

Thanks for the opportunity to review your PR @LOGESH-B 

Approving for merge

**Comment by gbowne1** [comment]
@LOGESH-B I believe I can fix this as I described in the issue during my time tomorrow.

Thanks for cleaning up the prettier errors.

Merging

**Comment by LOGESH-B** [comment]
I do check on other pages for any other error and I do change and then I merge it

**Comment by gbowne1** [comment]
I only see  a minor issue with CSS in the search bar 

I've been reviewing the console each page and with items open and closed and haven't found much yet.

We have some really good features. Waiting to see what @BlackBond06 & @ratishjain12 come up with

**Pull request merged**
