### PR TITLE
Adding Register UI

### PR DESCRIPTION
**Pull request by gbowne1**
This commit adds a Register or Sign Up page so that the user can register or sign up for the app.

It also adds the remaining fixes for the Login page UI including the initial CSS.

### CODE REVIEW

**Comment by LOGESH-B** [comment]
Hii @gbowne1 

npx eslint --fix . doesn't fix the problem
image

**Comment by gbowne1** [comment]
@LOGESH-B 

Yes, That is because they weren't defined.  ESLint won't fix undefined errors. I am going to work on that today later on as its 5am and commit the rest of the fix to this PR branch.

**Comment by gbowne1** [comment]
Login should be viewed at /login just fine

I don't think /register had a route yet so that won't show up.

**Comment by LOGESH-B** [comment]
> Login should be viewed at /login just fine
> 
> I don't think /register had a route yet so that won't show up.

No In login also same error
image

**Comment by gbowne1** [comment]
It won't render if you're on the master branch since it isn't merged yet.

There already is a /login route so should render just fine if you're on this PR branch.  

Either way I will fix this in a few hours and push to this PR branch.

Oh and if ESLint renders a X in the corner you should be able to close the error overlay and see what is rendering.

**Comment by gbowne1** [comment]
@LOGESH-B 

I believe I fixed it.  It should render just fine now.

The new login screen. Will render at /login
Screenshot 2023-07-28 at 14-57-47 React App

New Register screen UI. Will render at /register
Screenshot 2023-07-28 at 15-07-26 React App

I added a route for /register in App.js

**Review by LOGESH-B — APPROVED** [review]
Tested Locally Working fine ..Aproving for merge✌️

**Comment by gbowne1** [comment]
Thanks :+1:

**Pull request merged**
