### PR TITLE
Unit Test: Login and Signup

### PR DESCRIPTION
**Pull request by LOGESH-B**
#68  Here's the Updated unit Test for login and signup also solves the  issue #188

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally  for testing and review for merge

Tested this with the Jest extension in VSCode.  I am not sure what the msw package added is but, I reviewed the code for syntax errors, readability, formatting, spelling, etc.  These tests appear to work properly and pass with the extension.

Great work @LOGESH-B! This looks like it was done very well.  Thanks for your contribution and for the opportunity to review your PR.

Approving for merge.

**Comment by LOGESH-B** [comment]
> * [x]  Checked out this change locally  for testing and review for merge
> 
> Tested this with the Jest extension in VSCode. I am not sure what the msw package added is but, I reviewed the code for syntax errors, readability, formatting, spelling, etc. These tests appear to work properly and pass with the extension.
> 
> Great work @LOGESH-B! This looks like it was done very well. Thanks for your contribution and for the opportunity to review your PR.
> 
> Approving for merge.

@gbowne1  MSW package is used to mock the api calls from react

**Comment by gbowne1** [comment]
Oh, thanks.  I just had never seen that package before.  Good work!

**Review by BlackBond06 — APPROVED** [review]
Tested changes in PR locally for review and errors. Changes works as described in PR. Great work! @LOGESH-B, Thanks for the opportunity to review your PR.

**Pull request merged**
