### PR TITLE
User profile page

### LINKED ISSUE #50: [TODO] Create a User Profile Page
We do not currently have any means of users having profiles nor any means of the ability for users to create their own..

This issue is two parts:

- Create a user profile page accessible from user icon
- Create a form and methods in which the user can create their profile during their sign up or registration or account creation phase..

### PR DESCRIPTION
**Pull request by ratishjain12**
fixes #50 

@gbowne1 fixed merge conflicts

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review
- [x] reviewed manually for errors after checkout

This change works as expected. It adds the initial User Profile accessible by using the dropdown context menu by clicking on the (R) icon in the topnav and then clicking Profile.

I did not find that this change added any significant errors to the codebase and works as expected.

Approving for merge

**Comment by gbowne1** [comment]
@ratishjain12 @LOGESH-B @BlackBond06 Should we add a feature that would allow users to search the user database to find people who use the app who have read, reviewed, etc the same coding books in the database?

**Comment by BlackBond06** [comment]
100%. That will be very cool.

**Review by LOGESH-B — APPROVED** [review]
Hii @ratishjain12 
Thanks for your contribution✌️
Got some warnings, but it can be rectified in upcomming PRs
Approving for merge

**Pull request merged**
